# Generated by Django 4.0.3 on 2024-07-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='c',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
