# Generated by Django 4.0.3 on 2024-07-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quiz_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ans',
            field=models.CharField(choices=[(1, models.CharField(max_length=20)), (2, models.CharField(max_length=20)), (3, models.CharField(max_length=20)), (4, models.CharField(max_length=20))], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='que',
            field=models.CharField(max_length=100),
        ),
    ]
