# Generated by Django 4.0.3 on 2024-07-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_quiz_ans_alter_quiz_que'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_ans',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
