# Generated by Django 4.0.3 on 2024-07-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_data_test_attempt_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='eng_marks',
        ),
    ]
