# Generated by Django 4.0.3 on 2024-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_report_eng_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='totalEMarks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='totalFMarks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='totalMarks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='totalQue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
