# Generated by Django 4.0.3 on 2024-07-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_report_time_report_totalemarks_report_totalfmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='totalEMarks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='totalFMarks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='totalMarks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='totalQue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
