# Generated by Django 4.0.3 on 2024-07-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ngo_seminars'),
    ]

    operations = [
        migrations.CreateModel(
            name='techcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('level', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='ngo',
            name='note',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
