# Generated by Django 4.0.3 on 2024-07-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_report_totalemarks_alter_report_totalfmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
