# Generated by Django 4.0.3 on 2024-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_techcourse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
