# Generated by Django 4.0.3 on 2024-07-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_report_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcourse',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
