# Generated by Django 4.0.3 on 2024-07-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_ngo_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='engcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('level', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
