# Generated by Django 4.0.3 on 2024-07-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_makedonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='contact',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user_data',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='profilelink1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='profilelink2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='profilelink3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
