# Generated by Django 4.0.3 on 2024-07-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_user_data_contact_user_data_dob_user_data_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='pfp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
